### ISSUE TITLE
Decorated components does not work

### ISSUE THREAD

**Issue by zerkalica** [bruderstein/unexpected-react-shallow#2]
Some frameworks, like baobab, immutable-di, can decorate our components:
ex: https://github.com/zerkalica/immutable-di-starter-kit/blob/master/src/components/App.js
or: https://github.com/Paqmind/react-ultimate/blob/master/frontend/components/index/monster.js

Decorator looks like function, which wraps our react element to another and pass properties: https://github.com/zerkalica/immutable-di/blob/master/src/react/root.js

This test fails: https://github.com/zerkalica/immutable-di-starter-kit/blob/master/src/components/__tests__/AppTest.js

How to test markup inside WrappedApp -> App?

**Comment by bruderstein** [comment]
That's sadly a downside of the shallow renderer, in that it renders exactly one level, which in your case is the root component.

What you'd need to do is, after rendering your App component, use the shallow renderer again (or better a new one) to render the children of the first rendered component.

I can't test this at the moment, but I think it should work.

**Comment by zerkalica** [comment]
How to use renderer again for child components ?
This example does not work.

``` js
        const renderer = createRenderer()
        renderer.render(<App/>)

        const renderer2 = createRenderer()
        renderer2.render(renderer)

        expect(renderer2, 'to have rendered', <Layout/>)
```

**Comment by bruderstein** [comment]
I think:

``` js
        const renderer = createRenderer()
        renderer.render(<App/>)

        const renderer2 = createRenderer()
        renderer2.render(renderer.getRenderOutput())

        expect(renderer2, 'to have rendered', <Layout/>)
```

**Comment by zerkalica** [comment]
Thank you.
I wrote some helper:

``` js
// testHelpers.js
import unexpected from 'unexpected'
import unexpectedReactShallow from 'unexpected-react-shallow'
import React from 'react/addons'

const TestUtils = React.addons.TestUtils

export const expect = unexpected.clone().installPlugin(unexpectedReactShallow)

export function createRenderer(component, deep = 0) {
    let renderer = TestUtils.createRenderer()
    if (component) {
        renderer.render(component)
        if (deep > 0) {
            renderer = createRenderer(renderer.getRenderOutput(), deep - 1)
        }
    }

    return renderer
}
```

``` js
// AppTest.s

/* eslint-env mocha */
import React from 'react'

import {expect, createRenderer} from 'app/testHelpers'
import Layout from 'app/components/Layout'
import App from 'app/components/App'


describe('App', () => {
    it('should rendered', () => {
        expect(createRenderer(<App/>, 1), 'to have rendered', <Layout/>)
    })
})
```

**Comment by bruderstein** [comment]
Great stuff! I'll try and add that to the readme, I'm sure it would be useful for others.

That will probably be next week though, so don't worry if you don't see it yet.
