### ISSUE TITLE
Uncaught Error: Cannot find module "../package.json"

### ISSUE THREAD

**Issue by dlindahl** [bruderstein/unexpected-react-shallow#4]
I recently started getting this error during test runs when `unexpected-react-shallow` was installed into `unpexected`:

``` javascript
const expect = unexpected.clone().installPlugin(unexpectedReactShallow);
// Uncaught Error: Cannot find module "../package.json"
```

After a bit of digging, I was able to trace the source of the issue to a [line in `magicpen-prism`](https://github.com/unexpectedjs/magicpen-prism/blob/master/lib/magicPenPrism.js#L66) added in [a recent commit](https://github.com/unexpectedjs/magicpen-prism/commit/1c48e4121aba98277b3d984534727d2db33723e0) and released as part of `magicpen-prism` 2.2.1.

The quickest workaround was to specify a development dependency of `magicpen-prism` on 2.2.0 to prevent NPM from installing the now non-functional dependency on `magicpen-prism`.

I imagine this is only an issue when the test runner is running tests inside a web browser (like Karma, etc.). Since the `magicpen-prism` dependency is only `require`'d at runtime (and not "compile time"), Webpack (and likely Browserify) never have a chance to bundle up `magicpen-prism` and its dependency on its own `package.json` file. The `require('../package.json')` statement cannot possibly locate the desired file at that point, hence the exception.

A longer term solution might be to hoist the [`require` statement](https://github.com/bruderstein/unexpected-react-shallow/blob/master/src/unexpected-react-shallow.js#L19) up to the top of the file so that the dependency is pulled in at a time where Browserify/Webpack can see the dependency and bundle it up accordingly.

**Comment by bruderstein** [comment]
Thanks for reporting. I'll try and replicate it, but as far as I know, at least browserify will automatically pull in the require package.json, regardless of where it is (hence it will still be available if the require statement is inside an if statement) - at least that is my understanding. 

Maybe we can fix it in this project.

**Comment by bruderstein** [comment]
Sorry for the delay in response - the more I think about this, the more this doesn't add up. The package.json should just be there, the same as any other file would be. Have you by any chance got a demo repo I can try this out on?

**Comment by bruderstein** [comment]
I've been able to reproduce it now -https://github.com/bruderstein/shallow-issue-9

I can't see why, but hopefully that means we'll solve it

**Comment by bruderstein** [comment]
Solved!  You need to add the json-loader to your webpack config

``` js
{
    test: /\.json$/,
    loader: 'json'
}
```

Sorry for my lack of knowledge with webpack :(
