### ISSUE TITLE
React 0.14 compatibility

### ISSUE THREAD

**Issue by sunesimonsen** [bruderstein/unexpected-react-shallow#5]
Is there a reason for pinning the react version in the peer dependencies? I would like to use the plugin with react 0.14.0-rc1.

**Comment by bruderstein** [comment]
We're not yet compatible with the inline elements, and there are possibly other issues - it's certainly not yet tested with 0.14.  If it's alright with you, I'll change the title of this issue to "0.14 compatibility", then we can track it.

**Comment by sunesimonsen** [comment]
That sounds reasonable, I'll try it out with a fork then.

**Comment by bruderstein** [comment]
Fixed in 0.6.1
